id: P000124
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །འཆི་མེད་རིག་འཛིན་ཆེན་པོ་སྐུ་མི་མངོན་ཆོས་ཀྱི་དབྱིངས་སུ་གཤེགས་ཁར་གནང་བའི་ཞལ་གདམས་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། མཁས་གྲུབ་ཆེན་པོ་རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  layers:
  - book_title
  - author
  - chapter_title
  - yigchung
  id: TSD-TSE-16
web_metadata:
  title:
    en: The Last Testament of the Great Chime Rigzin Before His Passing Away
    bo: འཆི་མེད་རིག་འཛིན་ཆེན་པོ་སྐུ་མི་མངོན་ཆོས་ཀྱི་དབྱིངས་སུ་གཤེགས་ཁར་གནང་བའི་ཞལ་གདམས་བཞུགས་སོ།
  collection:
    en: Tsele Natsok Rangdrol Series–  Book 16
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།–  དེབ། ༡༦
  author:
    en: Tsele Natsok Rangdrol
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  pusblisher:
    en: Tsadra Foundation Publishing
    bo: ཙཱ་འདྲ་ཐེབས་རྩ་ཚོགས་པ།
  sku: TSD-TSE-16
  category:
    en: Pith Instructions
    bo: མན་ངག
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: TSD-TSE-16.epub
  description:
    en: ''
    bo: ''
